elog/urls.py
from django.urls import path

from . import views

app_name = 'elog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('sortRunType/', views.IndexView.as_view(), name='indexRunTypeSorted'),
    path('logForm/', views.logForm, name="logForm"),
    path('logForm/prevLog/', views.logFormWithPrev, name="logFormWithPrev"),
    path('logForm/addLog/', views.addLog, name="addLog"),
    path('logDetail/<int:pk>/', views.DetailView.as_view(), name="logDetail"),
    path('logDetail/<int:pk>/modifyLog/', views.modifyLog, name="modifyLog"),
    path('numData/', views.numData, name="numData"),
    path('graph/', views.graph, name="graph"),
]

elog/models.py
from django.db import models

# Create your models here.

class Log(models.Model):
    run_number = models.IntegerField(null=True)
    start_time = models.DateTimeField(null=True)
    stop_time = models.DateTimeField(null=True)
    fc73_begin = models.FloatField(default=0)
    fc74_begin = models.FloatField(default=0)
    fc75_begin = models.FloatField(default=0)
    d1_begin = models.FloatField(default=0)
    d2_begin = models.FloatField(default=0)
    ic_gas_pressure_begin = models.FloatField(default=0)
    fc73_end = models.FloatField(default=0)
    fc74_end = models.FloatField(default=0)
    fc75_end = models.FloatField(default=0)
    d1_end = models.FloatField(default=0)
    d2_end = models.FloatField(default=0)
    ic_gas_pressure_end = models.FloatField(default=0)
    scribe = models.CharField(max_length=50, default='')
    run_type = models.IntegerField(default=-1)
    trigger_type = models.IntegerField(default=-1)
    scaler1 = models.IntegerField(default=0) # OBJ Scint
    scaler2 = models.IntegerField(default=0) # XFP Scint
    scaler3 = models.IntegerField(default=0) # RED&BLUE
    title = models.CharField(max_length=200, default='')
    note = models.TextField(null=True, default='')

    runTypeText = ["Data", "Beam", "Calibration", "Trigger", "Note", "Junk"]

    triggerTypeText = ["Coincidence", "DS10", "Coinci.+DS50", "Secondary", "S800 singles", "CsI singles"]
    
    def getRunType(self):
        if (int(self.run_type) < len(self.runTypeText) and int(self.run_type) >= 0):
            return self.runTypeText[self.run_type]
        else:
            return "----"

    def getTriggerType(self):
        if (int(self.trigger_type) < len(self.triggerTypeText) and int(self.trigger_type) >= 0):
            return self.triggerTypeText[self.trigger_type]
        else:
            return "----"

    def getDuration(self):
        if self.start_time and self.stop_time:
            duration = self.stop_time - self.start_time
            values = divmod(duration.days * 86400 + duration.seconds, 3600)
            MnS = divmod(values[1], 60)
            if values[0] is not 0:
                return "%02d:%02d:%02d" % (values[0], MnS[0], MnS[1])
            else:
                MnS = divmod(values[1], 60)
                return "%02d:%02d" % (MnS[0], MnS[1])
        else:
            return ""

    def __str__(self):
        return "%d %s %s" % (self.run_number, self.getRunType(), self.title)

elog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

# Create your views here.

from itertools import chain

from django.views import generic
from django.utils import timezone

from .models import Log

class IndexView(generic.ListView):
    template_name = 'elog/index.html'
    context_object_name = 'logs'

    def get_queryset(self):
        name = self.request.resolver_match.url_name
        if name == 'indexRunTypeSorted':
            main = Log.objects.exclude(run_type=-1).order_by('run_type', '-start_time')
            sub = Log.objects.filter(run_type=-1).order_by('run_type', '-start_time')
            return list(chain(main, sub))
        else:
            return Log.objects.order_by('-run_number', '-start_time')

def logForm(request):
    return render(request, 'elog/logForm.html', {'runTypeTextList': Log.runTypeText, "triggerTypeTextList": Log.triggerTypeText})

def logFormWithPrev(request):
    log = Log.objects.order_by('-id')
    if log:
        log = log[0]
        return render(request, 'elog/logForm.html', {"runTypeTextList": Log.runTypeText, "triggerTypeTextList": Log.triggerTypeText, "prevLog": log})
    else:
        return render(request, 'elog/logForm.html', {"runTypeTextList": Log.runTypeText, "triggerTypeTextList": Log.triggerTypeText})

def addLog(request):
    log = Log()
    log.run_number = int(request.POST['runNumber'])
    log.start_time = timezone.datetime.now()
    log.stop_time = timezone.datetime.now()
    log.fc73_begin = float(request.POST['fc73Begin'])
    log.fc74_begin = float(request.POST['fc74Begin'])
    log.fc75_begin = float(request.POST['fc75Begin'])
    log.d1_begin = float(request.POST['d1Begin'])
    log.d2_begin = float(request.POST['d2Begin'])
    log.ic_gas_pressure_begin = float(request.POST['icGasPressureBegin'])
    log.ic_gas_pressure_begin = float(request.POST['icGasPressureBegin'])
    log.fc73_end = float(request.POST['fc73End'])
    log.fc74_end = float(request.POST['fc74End'])
    log.fc75_end = float(request.POST['fc75End'])
    log.d1_end = float(request.POST['d1End'])
    log.d2_end = float(request.POST['d2End'])
    log.ic_gas_pressure_end = float(request.POST['icGasPressureEnd'])
    log.scribe = request.POST['scribe']
    log.run_type = int(request.POST['runType'])
    log.trigger_type = int(request.POST['triggerType'])
    log.scaler1 = int(request.POST['scaler1'])
    log.scaler2 = int(request.POST['scaler2'])
    log.scaler3 = int(request.POST['scaler3'])
    log.title = request.POST['title']
    log.note = request.POST['note']
    log.save()
    return redirect('/elog/')

def modifyLog(request, pk):
    log = Log.objects.get(id=pk)
    log.run_number = int(request.POST['runNumber'])
    log.fc73_begin = float(request.POST['fc73Begin'])
    log.fc74_begin = float(request.POST['fc74Begin'])
    log.fc75_begin = float(request.POST['fc75Begin'])
    log.d1_begin = float(request.POST['d1Begin'])
    log.d2_begin = float(request.POST['d2Begin'])
    log.ic_gas_pressure_begin = float(request.POST['icGasPressureBegin'])
    log.fc73_end = float(request.POST['fc73End'])
    log.fc74_end = float(request.POST['fc74End'])
    log.fc75_end = float(request.POST['fc75End'])
    log.d1_end = float(request.POST['d1End'])
    log.d2_end = float(request.POST['d2End'])
    log.ic_gas_pressure_end = float(request.POST['icGasPressureEnd'])
    log.scribe = request.POST['scribe']
    log.run_type = int(request.POST['runType'])
    log.trigger_type = int(request.POST['triggerType'])
    log.scaler1 = int(request.POST['scaler1'])
    log.scaler2 = int(request.POST['scaler2'])
    log.scaler3 = int(request.POST['scaler3'])
    log.title = request.POST['title']
    log.note = request.POST['note']
    log.save()
    return redirect('/elog/')

class DetailView(generic.DetailView):
    model = Log
    template_name = 'elog/logDetail.html'

def numData(request):
    return HttpResponse(len(Log.objects.all()))

def graph(request):
    list = Log.objects.exclude(run_type=4).exclude(run_type=5).order_by('-start_time')
    if list[0].stop_time == None:
      return render(request, 'elog/graphs.html', {'logs':Log.objects.exclude(run_type=4).exclude(run_type=5).order_by('-start_time')[1:]})
    else:
      return render(request, 'elog/graphs.html', {'logs':Log.objects.exclude(run_type=4).exclude(run_type=5).order_by('-start_time')[0:]})

elog/templates/elog/graphs.html
{% load static %}
{% load elog_extras %}

<!DOCTYPE HTML>
<html>
  <head>
    <meta charset='UTF-8'>
    <title>HiRA elog</title>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js//popper.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/GenieStyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/highcharts.js' %}"></script>
    <script>
      jQuery(document).ready(function($) {
        var currentNumData;
        $.get("{% url 'elog:numData' %}", function( data ) {
            currentNumData = data;
        });
  
        var auto_refresh = setInterval(function () {
          $.get("{% url 'elog:numData' %}", function( data ) {
            if (currentNumData != data) {
              window.location.reload();
            }
          });
        }, 5000);
      });
  
      document.addEventListener('DOMContentLoaded', function () {
        Highcharts.chart('scalerRatios', {
          chart: {
            type: 'line'
          },
          title: {
            text: 'Scaler ratios (last 30 runs)'
          },
          xAxis: {
            type: 'number',
            title: {
              text: 'Run number'
            }
          },
          yAxis: {
            type: 'number',
            title: {
              text: 'Ratios'
            }
          },

          plotOptions: {
            line: {
              dataLabels: {
                enabled: false
              },
              enableMouseTracking: true
            }
          },

          colors: ['#FF0000', '#00FF00', '#0000FF', '#036', '#000'],

          series: [{
            name: "OBJ/XFP",
            data: [
              {% for entry in logs|slice:":30" %}
              [{{ entry.run_number }}, {{ entry.scaler1|div:entry.scaler2|floatformat:4 }}]{% if forloop.counter0 < 30 %},{% endif %}
              {% endfor %}
            ]},{
            name: "R&B/OBJ",
            data: [
              {% for entry in logs|slice:":30" %}
              [{{ entry.run_number }}, {{ entry.scaler3|div:entry.scaler1|floatformat:4 }}]{% if forloop.counter0 < 30 %},{% endif %}
              {% endfor %}
            ]},{
            name: "R&B/XFP",
            data: [
              {% for entry in logs|slice:":30" %}
              [{{ entry.run_number }}, {{ entry.scaler3|div:entry.scaler2|floatformat:4 }}]{% if forloop.counter0 < 30 %},{% endif %}
              {% endfor %}
            ]
          }]
        });
        Highcharts.chart('gasPressure', {
          chart: {
            type: 'line'
          },
          title: {
            text: 'IC Gas Pressure (last 30 runs)'
          },
          xAxis: {
            type: 'number',
            title: {
              text: 'Run number'
            }
          },
          yAxis: {
            type: 'number',
            title: {
              text: 'Pressure [torr]'
            }
          },
          plotOptions: {
            line: {
              dataLabels: {
                enabled: false
              },
              enableMouseTracking: true
            }
          },

          colors: ['#FF0000', '#00FF00', '#0000FF', '#036', '#000'],

          series: [{
            name: "IC Gas Pressure (begin)",
            data: [
              {% for entry in logs|slice:":30" %}
              [{{ entry.run_number }}, {{ entry.ic_gas_pressure_begin }}]{% if forloop.counter0 < 30 %},{% endif %}
              {% endfor %}
            ]
          }]
        });

        Highcharts.chart('scalerRatiosAll', {
          chart: {
            type: 'line'
          },
          title: {
            text: 'Scaler ratios (All runs)'
          },
          xAxis: {
            type: 'number',
            title: {
              text: 'Run number'
            }
          },
          yAxis: {
            type: 'number',
            title: {
              text: 'Ratios'
            }
          },

          plotOptions: {
            line: {
              dataLabels: {
                enabled: false
              },
              enableMouseTracking: true
            }
          },

          colors: ['#FF0000', '#00FF00', '#0000FF', '#036', '#000'],

          series: [{
            name: "OBJ/XFP",
            data: [
              {% for entry in logs %}
              [{{ entry.run_number }}, {{ entry.scaler1|div:entry.scaler2|floatformat:4 }}]{% if not forloop.last %},{% endif %}
              {% endfor %}
            ]},{
            name: "R&B/OBJ",
            data: [
              {% for entry in logs %}
              [{{ entry.run_number }}, {{ entry.scaler3|div:entry.scaler1|floatformat:4 }}]{% if not forloop.last %},{% endif %}
              {% endfor %}
            ]},{
            name: "R&B/XFP",
            data: [
              {% for entry in logs %}
              [{{ entry.run_number }}, {{ entry.scaler3|div:entry.scaler2|floatformat:4 }}]{% if not forloop.last %},{% endif %}
              {% endfor %}
            ]
          }]
        });

        Highcharts.chart('gasPressureAll', {
          chart: {
            type: 'line'
          },
          title: {
            text: 'IC Gas Pressure (All runs)'
          },
          xAxis: {
            type: 'number',
            title: {
              text: 'Run number'
            }
          },
          yAxis: {
            type: 'number',
            title: {
              text: 'Pressure [torr]'
            }
          },
          plotOptions: {
            line: {
              dataLabels: {
                enabled: false
              },
              enableMouseTracking: true
            }
          },

          colors: ['#FF0000', '#00FF00', '#0000FF', '#036', '#000'],

          series: [{
            name: "IC Gas Pressure (begin)",
            data: [
              {% for entry in logs %}
              [{{ entry.run_number }}, {{ entry.ic_gas_pressure_begin }}]{% if not forloop.last %},{% endif %}
              {% endfor %}
            ]
          }]
        });
      });
    </script>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row justify-content-sm-center">
        <div class="col">
          <div id="scalerRatios" style="width:100%; height:350px;"></div>
        </div>
        <div class="col">
          <div id="gasPressure" style="width:100%; height:350px;"></div>
        </div>
      </div>
      <div class="row justify-content-sm-center">
        <div class="col">
          <div id="scalerRatiosAll" style="width:100%; height:350px;"></div>
        </div>
        <div class="col">
          <div id="gasPressureAll" style="width:100%; height:350px;"></div>
        </div>
      </div>
    </div>
  </body>
</html>

elog/templates/elog/index.html
{% load static %}
{% load elog_extras %}

<!DOCTYPE HTML>
<html>
  <head>
    <meta charset='UTF-8'>
    <title>HiRA elog</title>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js//popper.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/GenieStyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </head>
  <script>
    jQuery(document).ready(function($) {
      $('table').on('click', 'tbody', function(){
        $('table').find('tbody').removeClass('selected');
        $(this).addClass('selected');
          window.location = $(this).data("href");
      });

      var currentNumData;
      $.get("{% url 'elog:numData' %}", function( data ) {
          currentNumData = data;
      });

      var auto_refresh = setInterval(function () {
        $.get("{% url 'elog:numData' %}", function( data ) {
          if (currentNumData != data) {
            $(location).attr('href', '{% if request.path == '/elog/' %}{% url 'elog:index' %}{% else %}{% url 'elog:indexRunTypeSorted' %}{% endif %}');
          }
        });
      }, 5000);
    });
  </script>
  <style>
    tbody:hover tr { background-color: #eee;  }
    tbody.selected tr { background-color: #eee; }
  </style>
  <body>
    <div class="container-fluid">
      <p><h1>HiRA elog - e18015</h1></p>
      <p align="center">
      <a href="{% url 'elog:logForm' %}" class="btn btn-success btn-sm">Add new log</a>
      <a href="{% url 'elog:logFormWithPrev' %}" class="btn btn-info btn-sm">Add log with the last entry</a>
      <a href="" class="btn btn-primary btn-sm">Reload</a>
      </p>
      <table class="tableMargin table table-hover table-sm">
        <thead>
          <tr class="bg-success">
            <th scope="col" width="80px"><a href="{% url 'elog:index' %}" style="color:black">Run#{% if request.path == '/elog/' %} ▼{% endif %}</a></td>
            <th scope="col" width="100px">Start time</td>
            <th scope="col" width="100px">Stop time</td>
            <th scope="col" width="110px">Run length</td>
            <th scope="col" width="120px"><a href="{% url 'elog:indexRunTypeSorted' %}" style="color:black">Run type{% if request.path == '/elog/sortRunType/' %} ▼{% endif %}</a></td>
            <th scope="col" width="120px">Trigger</td>
<!--            <th scope="col" width="80px">FC73</td> -->
<!--            <th scope="col" width="80px">FC74</td> -->
            <th scope="col" width="80px">FC75</td>
            <th scope="col" width="80px">D1</td>
            <th scope="col" width="80px">D2</td>
            <th scope="col" width="80px">IC Gas P</td>
            <th scope="col" width="85px">XFP Scint</td>
            <th scope="col" width="85px">OBJ Scint</td> <!-- SWAP 1-->
            <th scope="col" width="85px">RED&BLUE</td>
            <th scope="col" width="85px">OBJ/XFP</td>
            <th scope="col" width="85px">R&B/OBJ</td>
            <th scope="col" width="85px">R&B/XFP</td>
        
            <th scope="col">Title</td>
          </tr>
        </thead>
          {% for logEntry in logs %}
        <tbody data-href="{% url 'elog:logDetail' logEntry.pk %}">
          <tr>
            <th scope="row" rowspan="2" class="align-middle">{{ logEntry.run_number }}</td>
            <td rowspan=2 class="align-middle">{{ logEntry.start_time|date:"m/d H:i" }}</td>
            <td rowspan=2 class="align-middle">{{ logEntry.stop_time|date:"m/d H:i" }}</td>
            <td rowspan=2 class="align-middle">{{ logEntry.getDuration }}</td>
            <td rowspan=2 class="align-middle">{{ logEntry.getRunType }}</td>
            <td rowspan=2 class="align-middle">{{ logEntry.getTriggerType }}</td>
<!--            <td>{{ logEntry.fc73_begin }}</td> -->
<!--            <td>{{ logEntry.fc74_begin }}</td> -->
            <td>{{ logEntry.fc75_begin }}</td>
            <td>{{ logEntry.d1_begin|floatformat:4 }}</td>
            <td>{{ logEntry.d2_begin|floatformat:4 }}</td>
            <td>{{ logEntry.ic_gas_pressure_begin }}</td>
            <td rowspan=2 class="align-middle">{{ logEntry.scaler2 }}</td>
            <td rowspan=2 class="align-middle">{{ logEntry.scaler1 }}</td>
            <td rowspan=2 class="align-middle">{{ logEntry.scaler3 }}</td>
            <td rowspan=2 class="align-middle">{{ logEntry.scaler1|div:logEntry.scaler2|floatformat:4 }}</td>
            <td rowspan=2 class="align-middle">{{ logEntry.scaler3|div:logEntry.scaler1|floatformat:4 }}</td>
            <td rowspan=2 class="align-middle">{{ logEntry.scaler3|div:logEntry.scaler2|floatformat:4 }}</td>
            <td rowspan=2 class="align-middle">{{ logEntry.title|truncatechars:110 }}</td>
          </tr>
          <tr>
<!--            <td>{{ logEntry.fc73_end }}</td> -->
<!--            <td>{{ logEntry.fc74_end }}</td> -->
            <td>{{ logEntry.fc75_end }}</td>
            <td>{{ logEntry.d1_end|floatformat:4 }}</td>
            <td>{{ logEntry.d2_end|floatformat:4 }}</td>
            <td>{{ logEntry.ic_gas_pressure_end }}</td>
          </tr>
        </tbody>
          {% endfor %}
      </table>
    </div>
  </body>
</html>

elog/templates/elog/logDetail.html
{% load static %}

<!DOCTYPE HTML>
<html>
  <head>
    <meta charset='UTF-8'>
    <title>HiRA elog</title>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js//popper.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/GenieStyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
      $(document).ready(function(){
        var applyChange = function() {
          var scaler1 = $('input[name=scaler1]').val();
          var scaler2 = $('input[name=scaler2]').val();
          var scaler3 = $('input[name=scaler3]').val();
          $('input[name=calc1]').attr('placeholder', scaler3/scaler1);
          $('input[name=calc2]').attr('placeholder', scaler3/scaler2);
          $('input[name=calc3]').attr('placeholder', scaler1/scaler2);
        };

        applyChange();

        $('input[name=scaler1]').keyup(applyChange);
        $('input[name=scaler2]').keyup(applyChange);
        $('input[name=scaler3]').keyup(applyChange);
      });
    </script>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-sm-center">
        <div class="col-sm-10">
          <h1>Log detail</h1>
        </div>
      </div>
      <form action="{% url 'elog:modifyLog' log.id %}" method="post">
        {% csrf_token %}
        <div class="form-group row justify-content-sm-center">
          <div class="col-sm-5" style="text-align:left">
            <a href="{% url 'elog:index' %}"><button type="button" class="btn btn-secondary btn-sm">Back</button></a>
          </div>
          <div class="col-sm-5" style="text-align:right">
            <input type="submit" class="btn btn-primary btn-sm" value="Save modifications">
          </div>
        </div>
        <div class="form-row justify-content-sm-center">
          <div class="form-group col-sm-2">
            <label for="runNumber">Run number</label>
            <input type="number" class="form-control form-control-sm" name="runNumber" value="{{ log.run_number }}">
          </div>
          <div class="form-group col-sm-3">
            <label for="startTime">Start time</label>
            <input type="text" class="form-control form-control-sm" name="startTime" placeholder="{{ log.start_time|date:"m/d/Y H:i:s" }}" readonly>
          </div>
          <div class="form-group col-sm-3">
            <label for="stopTime">Stop time</label>
            <input type="text" class="form-control form-control-sm" name="stopTime" placeholder="{{ log.stop_time|date:"m/d/Y H:i:s" }}" readonly>
          </div>
          <div class="form-group col-sm-2">
            <label for="runLength">Run length</label>
            <input type="text" class="form-control form-control-sm" name="runLength" placeholder="{{ log.getDuration }}" readonly>
          </div>
        </div>
        <div class="form-row justify-content-sm-center">
          <div class="form-group col-sm-2">
          </div>
          <div class="form-group col-sm-2">
            <label for="fc73Begin">FC73</label>
            <div class="form-row">
              <div class="col">
                <input type="number" class="form-control form-control-sm" name="fc73Begin" step="0.00001" value="{{ log.fc73_begin }}">
              </div>
              <div class="col">
                <input type="number" class="form-control form-control-sm" name="fc73End" step="0.00001" value="{{ log.fc73_end }}">
              </div>
            </div>
          </div>
          <div class="form-group col-sm-2">
            <label for="fc74Begin">FC74</label>
            <div class="form-row">
              <div class="col">
                <input type="number" class="form-control form-control-sm" name="fc74Begin" step="0.00001" value="{{ log.fc74_begin }}">
              </div>
              <div class="col">
                <input type="number" class="form-control form-control-sm" name="fc74End" step="0.00001" value="{{ log.fc74_end }}">
              </div>
            </div>
          </div>
          <div class="form-group col-sm-2">
            <label for="fc75Begin">FC75</label>
            <div class="form-row">
              <div class="col">
                <input type="number" class="form-control form-control-sm" name="fc75Begin" step="0.00001" value="{{ log.fc75_begin }}">
              </div>
              <div class="col">
                <input type="number" class="form-control form-control-sm" name="fc75End" step="0.00001" value="{{ log.fc75_end }}">
              </div>
            </div>
          </div>
          <div class="form-group col-sm-2">
          </div>
        </div>
        <div class="form-row justify-content-sm-center">
          <div class="form-group col-sm-2">
            <label for="scribe">Scribe</label>
            <input type="text" class="form-control form-control-sm" name="scribe" value="{{ log.scribe }}" required>
          </div>
          <div class="form-group col-sm-2">
            <label for="d1">D1</label>
            <div class="form-row">
              <div class="col">
                <input type="number" class="form-control form-control-sm" name="d1Begin" step="0.00001" value="{{ log.d1_begin }}">
              </div>
              <div class="col">
                <input type="number" class="form-control form-control-sm" name="d1End" step="0.00001" value="{{ log.d1_end }}">
              </div>
            </div>
          </div>
          <div class="form-group col-sm-2">
            <label for="d2">D2</label>
            <div class="form-row">
              <div class="col">
                <input type="number" class="form-control form-control-sm" name="d2Begin" step="0.00001" value="{{ log.d2_begin }}">
              </div>
              <div class="col">
                <input type="number" class="form-control form-control-sm" name="d2End" step="0.00001" value="{{ log.d2_end }}">
              </div>
            </div>
          </div>
          <div class="form-group col-sm-2">
            <label for="icGasPressureBegin">S800 IC Gas Pressure</label>
            <div class="form-row">
              <div class="col">
                <input type="number" class="form-control form-control-sm" name="icGasPressureBegin" step="0.0001" value="{{ log.ic_gas_pressure_begin }}">
              </div>
              <div class="col">
                <input type="number" class="form-control form-control-sm" name="icGasPressureEnd" step="0.0001" value="{{ log.ic_gas_pressure_end }}">
              </div>
            </div>
          </div>
          <div class="form-group col-sm-2">
          </div>
        </div>
        <div class="form-row justify-content-sm-center">
          <div class="form-group col-sm-2">
            <label for="runType">Run type</label>
            <select class="form-control form-control-sm" name="runType">
              <option value="-1">----</option>
              {% for runTypeText in log.runTypeText %}
              <option value={{ forloop.counter0 }} {% if log.run_type == forloop.counter0 %} selected {% endif %}>{{ runTypeText }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group col-sm-2">
            <label for="triggerType">Trigger type</label>
            <select class="form-control form-control-sm" name="triggerType">
              <option value="-1">----</option>
              {% for triggerTypeText in log.triggerTypeText %}
              <option value={{ forloop.counter0 }} {% if log.trigger_type == forloop.counter0 %} selected {% endif %}>{{ triggerTypeText }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group col-sm-1">
            <label for="scaler1">OBJ Scint</label>
            <input type="number" class="form-control form-control-sm" name="scaler1" step="1" value="{{ log.scaler1 }}">
          </div>
          <div class="form-group col-sm-1">
            <label for="scaler2">XFP Scint</label>
            <input type="number" class="form-control form-control-sm" name="scaler2" step="1" value="{{ log.scaler2 }}">
          </div>
          <div class="form-group col-sm-1">
            <label for="scaler3">Red&Blue</label>
            <input type="text" class="form-control form-control-sm" name="scaler3" step="1" value="{{ log.scaler3 }}">
          </div>
          <div class="form-group col-sm-1">
            <label for="calc1">R&B/OBJ</label>
            <input type="text" class="form-control form-control-sm" name="calc1" placeholder="" readonly>
          </div>
          <div class="form-group col-sm-1">
            <label for="calc2">R&B/XFP</label>
            <input type="text" class="form-control form-control-sm" name="calc2" placeholder="" readonly>
          </div>
          <div class="form-group col-sm-1">
            <label for="calc3">OBJ/XFP</label>
            <input type="text" class="form-control form-control-sm" name="calc3" placeholder="" readonly>
          </div>
        </div>
        <div class="form-row justify-content-sm-center">
          <div class="form-group col-sm-10">
            <label for="title">Title</label>
            <input type="text" class="form-control form-control-sm" name="title" value="{{ log.title }}">
          </div>
        </div>
        <div class="form-row justify-content-sm-center">
          <div class="form-group col-sm-10">
            <label for="note">Note</label>
            <textarea class="form-control form-control-sm" name="note" rows="8">{{ log.note }}</textarea>
          </div>
        </div>
      </form>
    </div>
  </body>
</html>